<h1 class="text-center">Membres du groupe</h1>
<div class="card-deck">
    <div class="card">
        <img src="<?= $rootUri ?>/public/images/Anthony.jpg" class="img-fluid" alt="Anthony Pernot">
        <div class="card-body">
            <h5 class="card-title">Anthony Pernot</h5>
        </div>
    </div>
    <div class="card">
        <img src="<?= $rootUri ?>/public/images/Jules.jpg" class="img-fluid" alt="Jules Sayer">
        <div class="card-body">
            <h5 class="card-title">Jules Sayer</h5>
        </div>
    </div>
    <div class="card">
        <img src="<?= $rootUri ?>/public/images/Nathan.jpg" class="img-fluid" alt="Nathan Chevalier">
        <div class="card-body">
            <h5 class="card-title">Nathan Chevalier</h5>
        </div>
    </div>
</div>