<h1 class="text-center">Membres du groupe</h1>
<div class="card-deck">
    <div class="card">
        <img src="<?= $rootUri ?>/public/images/Anthony.jpg" class="img-fluid" alt="Anthony Pernot" >
        <div class="card-body">
            <h5 class="card-title">Anthony Pernot</h5>
        </div>
    </div>
    <div class="card">
        <img src="<?= $rootUri ?>/public/images/Jules.jpg" class="img-fluid" alt="Jules Sayer">
        <div class="card-body">
            <h5 class="card-title">Jules Sayer</h5>
        </div>
    </div>
    <div class="card">
        <img src="<?= $rootUri ?>/public/images/Nathan.jpg" class="img-fluid" alt="Nathan Chevalier">
        <div class="card-body">
            <h5 class="card-title">Nathan Chevalier</h5>
        </div>
    </div>
</div>

<h2 class="text-center"> MyWishList.app </h2>
<p class="text-left">
    L'application à réaliser est décrite sous la forme de fonctionnalités élémentaires, classées dans 6 grands cas d'utilisation.
    Attention : il est peut-être impossible de programmer toutes les fonctionnalités sur le temps prévu.
    Choisissez de faire d'abord celles qui paraissent les plus indispensables : l'objectif est d'avoir une application fonctionnelle même si elle n'est pas complète.
    Une base de données contenant des items rassemblés par liste, avec leur descriptif et une photo, vous est fournie.
    Elle vous permettra de tester et faire fonctionner un grand nombre des fonctionnalités attendues.
</p>


