<?php if (isset($flash['error'])) foreach ($flash['error'] as $m): ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Mince!</strong> <?= $m ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
<?php if (isset($flash['success'])) foreach ($flash['success'] as $m): ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Super!</strong> <?= $m ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Modifier mon compte</h4>
                <form method="POST" action="<?= $router->pathFor('updateAccount') ?>">
                    <div class="form-group">
                        <label for="pseudo">Pseudonyme</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">@</div>
                            </div>
                            <input id="pseudo" type="text" class="form-control" name="pseudo" value="<?= $_SESSION['user']->pseudo ?>" disabled>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email">Adresse e-mail</label>
                        <input id="email" type="email" class="form-control" name="email" value="<?= $_SESSION['user']->email ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="password">Mot de passe actuel</label>
                        <input id="password" type="password" class="form-control" name="password" required>
                    </div>

                    <div class="form-group m-0">
                        <button type="submit" class="btn btn-primary btn-block">
                            Enregistrer
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Modifier mon mot de passe</h4>
                <form method="POST" action="<?= $router->pathFor('updatePassword') ?>">
                    <div class="form-group">
                        <label for="actual_password">Mot de passe actuel</label>
                        <input id="actual_password" type="password" class="form-control" name="password" required>
                    </div>
                    <div class="form-group">
                        <label for="new_password">Nouveau mot de passe</label>
                        <input id="new_password" type="password" class="form-control" name="new_password" required>
                    </div>
                    <div class="form-group">
                        <label for="new_password_conf">Confirmation</label>
                        <input id="new_password_conf" type="password" class="form-control" name="new_password_conf" required>
                    </div>

                    <div class="form-group m-0">
                        <button type="submit" class="btn btn-primary btn-block">
                            Enregistrer
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
