<?php if (isset($flash['error'])) foreach ($flash['error'] as $m): ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Mince!</strong> <?= $m ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
<?php if (isset($flash['success'])) foreach ($flash['success'] as $m): ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Super!</strong> <?= $m ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
   <!-- Modal Suppression Compte -->
   <div class="modal fade" id="suppAccount<?= $user->pseudo ?>" tabindex="-1" role="dialog" aria-labelledby="suppAccountLabel" aria-hidden="true">
         <div class="modal-dialog" role="document">
             <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="suppAccountLabel"><?= $user->pseudo ?> - Suppression de compte</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                    <form method="POST" action="<?= $router->pathFor('deleteAccount') ?>" >
                         <div class="modal-body">
                                <blockquote class="blockquote text-center">
                                    <p class="mb-0">Êtes-vous sûr de supprimer votre compte ? </p><br>
                                    <footer class="blockquote-footer">La suppression de votre compte entraîne la suppression des listes, des items et images, des participations uniquement avant échéance et de tous les messages</footer>
                                </blockquote>
                         </div>
                         <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-toggle="modal" role="button" data-dismiss="modal">Fermer</button>
                              <button type="submit" class="btn btn-primary">Poursuivre</button>
                         </div>
                    </form>
                
             </div>
        </div>
    </div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Modifier mon compte</h4>
                <form method="POST" action="<?= $router->pathFor('updateAccount') ?>">
                    <div class="form-group">
                        <label for="pseudo">Pseudonyme</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">@</div>
                            </div>
                            <input id="pseudo" type="text" class="form-control" name="pseudo" value="<?= $_SESSION['user']->pseudo ?>" disabled>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email">Adresse e-mail</label>
                        <input id="email" type="email" class="form-control" name="email" value="<?= $_SESSION['user']->email ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="password">Mot de passe actuel</label>
                        <input id="password" type="password" class="form-control" name="password" required>
                    </div>

                    <div class="form-group m-0">
                        <button type="submit" class="btn btn-primary btn-block">
                            Enregistrer
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Modifier mon mot de passe</h4>
                <form method="POST" action="<?= $router->pathFor('updatePassword') ?>">
                    <div class="form-group">
                        <label for="actual_password">Mot de passe actuel</label>
                        <input id="actual_password" type="password" class="form-control" name="password" required>
                    </div>
                    <div class="form-group">
                        <label for="new_password">Nouveau mot de passe</label>
                        <input id="new_password" type="password" class="form-control" name="new_password" required>
                    </div>
                    <div class="form-group">
                        <label for="new_password_conf">Confirmation</label>
                        <input id="new_password_conf" type="password" class="form-control" name="new_password_conf" required>
                    </div>

                    <div class="form-group m-0">
                        <button type="submit" class="btn btn-primary btn-block">
                            Enregistrer
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>   
</div>
<div class="card">
    <div class="card body">
        <a class="btn btn-danger" data-toggle="modal" href="#suppAccount<?= $user->pseudo ?>" role="button"  aria-controls="collapseExample"> Supprimer son compte </a>
    </div>
</div><!--aria-expanded="false"
<a class="btn btn-sm btn-primary" data-toggle="modal" href="#uploadImage<?= $item->id ?>" role="button" data-dismiss="modal" >
-->