<div class="alert alert-dark" role="alert">
    <h4 class="alert-heading">Espace Administration</h4>
    <p>C'est à partir de cette page que vous pouvez effectuer des actions sur votre liste.</p>
    <hr>
    <p class="mb-0">Vous modifiez actuellement la liste «<?= $liste->titre ?>»</p>
</div>
<div class="row">
    <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="general-tab" data-toggle="pill" href="#general" role="tab" aria-controls="general" aria-selected="true">Général</a>
        </div>
    </div>
    <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
                <div class="card">
                    <div class="card-header">
                        Général
                    </div>
                    <div class="card-body">
                        <form id="form_message" method="POST" action="<?= $router->pathFor('updateListe', ['token' => $liste->token, 'creationToken' => $liste->creationToken]) ?>">
                            <div class="form-group">
                                <label for="inputName">Titre</label>
                                <input type="text" name="newTitle" class="form-control" id="inputTitle" value="<?= $liste->titre ?>">
                            </div>
                            <div class="form-group">
                                <label for="inputName">Date d'expiration</label>
                                <input type="date" name="newDate" class="form-control" id="inputDateExpi" value="<?= $liste->expiration ?>">
                            </div>
                            <div class="form-group">
                                <label for="textarea">Description</label>
                                <textarea class="form-control" id="textarea" rows="3" name="newDescription"><?= $liste->description ?></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-primary float-right">Envoyer</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
            <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
        </div>
    </div>
</div>