<h2 class="text-center my-5">Création de l'item</h2>
<form id="form_message" method="POST" action="<?= $router->pathFor('createItem') ?>">
<input type="hidden" value="<?= $liste->token ?>" name="token"/>
    <input type="hidden" value="<?= $liste->creationToken ?>" name="creationToken"/>
    <div class="form-group">
        <label for="inputName">Insérez un nom d'item</label>
        <input type="text" name="nom" class="form-control" id="inputName">
    </div>
    
    <div class="form-group">
        <label for="inputPrix">Insérez un prix</label>
        <input type="number" name="prix" class="form-control" id="inputPrix">
    </div>
    <div class="form-group">
        <label for="inputFile">Insérez une image</label>
        <input type="file" accept="image/png, image/jpg, image/jpeg" name="file" class="form-control" id="inputFile">
    </div>
    <div class="form-group">
        <label for="inputUrl">Insérez un lien correspondant à l'item</label>
        <div class="shadow p-3 mb-5 bg-white rounded">L'url n'est pas obligatoire, il permet de donner plus d'informations sur l'item en question</div>
        <input type="url" name="url" class="form-control" id="inputUrl">
    </div>
    <div class="form-group">
        <label for="textarea">Ajoutez une description</label>
        <textarea class="form-control" id="textarea" rows="3" name="descr"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>