<h2 class="text-center my-5">Création de liste</h2>
<form method="POST" action="<?= $router->pathFor('createListe') ?>">
    <div class="form-group">
        <label for="inputName">Insérez un titre</label>
        <input type="text" name="titre" class="form-control" id="inputTitle">
    </div>
    <div class="form-group">
        <label for="inputName">Indiquez une date d'expiration</label>
        <input type="date" name="dateExpi" class="form-control" id="inputDateExpi">
    </div>
    <div class="form-group">
        <label for="textarea">Ajoutez une description</label>
        <textarea class="form-control" id="textarea" rows="3" name="descr"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>