<div class="d-flex justify-content-center align-items-center my-4" id="error">
    <h1 class="mr-3 pr-3 align-top border-right inline-block align-content-center"><?= $ERROR_CODE ?></h1>
    <div class="inline-block align-middle">
        <h2 class="font-weight-normal lead" id="desc"><?= $ERROR_TEXT ?></h2>
        <input type="button" class="font-weight-normal lead btn btn-block btn-primary" value="Retour" onclick="window.history.back()" />
    </div>
</div>