<?php if (isset($flash['error'])) foreach ($flash['error'] as $m): ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Mince!</strong> <?= $m ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
<?php if (isset($flash['success'])) foreach ($flash['success'] as $m): ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Super!</strong> <?= $m ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endforeach; ?>
<div class="row">
    <div class="col">
        <div class="jumbotron my-2">
            <p class="display-4">Bienvenue sur MyWishList!</p>
            <p class="lead">Ce projet a été réalisé dans le cadre du module de Prog. Web/Serveur @IUT-NC 2019.</p>
        </div>
    </div>
    <div class="col">
        <?php if(!empty($listes)): ?>
            <p class="display-4 text-center">Listes publique:</p>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Date d'expiration</th>
                    <th scope="col">Accéder à la liste</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($listes as $liste): ?>
                    <tr>
                        <td><?= $liste->titre ?></td>
                        <td><?= date("d/m/Y", strtotime($liste->expiration)) ?></td>
                        <td><a class="btn btn-primary" href="<?= $router->pathFor('showListe', ['token' => $liste->token]) ?>">Accéder à la liste</a></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
</div>