<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $router->pathFor('home') ?>">Accueil</a></li>
        <li class="breadcrumb-item active" aria-current="page">Listes</li>
    </ol>
</nav>
<table class="table table-hover table-striped">
    <thead>
        <br>
        <tr>
            <th scope="col">Numéro</th>
            <th scope="col">ID users</th>
            <th scope="col">Titre</th>
            <th scope="col">Description</th>
            <th scope="col">Expiration</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($listes as $liste) : ?>
            <tr>
                <th scope="row"><?= $liste->no ?></th>
                <td><?= $liste->user_id ?></td>
                <td><?= $liste->titre ?></td>
                <td><?= $liste->description ?></td>
                <td><?= $liste->expiration ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>