<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Numéro</th>
            <th scope="col">ID utilisateur</th>
            <th scope="col">Titre</th>
            <th scope="col">Description</th>
            <th scope="col">Expiration</th>
            <th scope="col">Token</th>
        </tr>
    </thead>
    <tbody>
<?php foreach($lists as $list): ?>
        <tr>
            <th scope="row"><?= $list->no ?></th>
            <td><?= $list->user_id ?></td>
            <td><?= $list->titre ?></td>
            <td><?= $list->description ?></td>
            <td><?= $list->expiration ?></td> 
            <td><?= $list->token ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>