<div class="card text-center my-2">
  <div class="card-header">
    <?= $liste->titre ?>
  </div>
  <div class="card-body">
    <p class="card-text"><?= $liste->user_id ?></p>
    <p class="card-text"><?= $liste->description ?></p>
    <p class="card-text"><?= $liste->expiration ?></p>
  </div>
</div>
<div class="row row-cols-1 row-cols-md-3">
  <?php foreach ($items as $item) : ?>
    <div class="col mb-4">
      <div class="card h-100 my-2">
        <img class="card-img-top" src="<?= $rootUri ?>/public/images/<?= $item->img ?>" alt="Card image cap">
        <div class="card-img-overlay">
          <p class="card-text badge badge-warning"><?= $item->tarif ?> €</p>
        </div>
        <div class="card-body">
          <h3 class="card-title"><?= $item->nom ?></h3>
          <p class="card-text"><?= $item->descr ?></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Liste n°<?= $item->liste_id ?>, objet n°<?= $item->id ?></small>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>