<div class="card">
    <div class="card-body">
        <h4 class="card-title">Connexion</h4>
        <form method="POST" action="<?= $router->pathFor('showRegister') ?>">
            <div class="form-group">
                <label for="pseudo">Pseudonyme / Adresse e-mail</label>
                <div class="input-group">
                    <input id="pseudo" type="text" class="form-control" name="id" required>
                </div>
            </div>

            <div class="form-group">
                <label for="email">Mot de passe</label>
                <input id="password" type="password" class="form-control" name="password" required>
            </div>

            <div class="form-group m-0">
                <button type="submit" class="btn btn-primary btn-block">
                    Se connecter
                </button>
            </div>
            <div class="mt-4 text-center">
                Vous n'avez pas de compte? <a href="<?= $router->pathFor('showRegister') ?>">Inscrivez-vous!</a>
            </div>
        </form>
    </div>
</div>