<div class="card">
    <div class="card-body">
        <h4 class="card-title">Connexion</h4>
        <?php if (isset($flash['error'])) foreach ($flash['error'] as $m): ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Mince!</strong> <?= $m ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <?php endforeach; ?>
        <?php if (isset($flash['success'])) foreach ($flash['success'] as $m): ?>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Super!</strong> <?= $m ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <?php endforeach; ?>
        <form method="POST" action="<?= $router->pathFor('login') ?>">
            <div class="form-group">
                <label for="pseudo">Pseudonyme / Adresse e-mail</label>
                <div class="input-group">
                    <input id="pseudo" type="text" class="form-control" name="id" required>
                </div>
            </div>

            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input id="password" type="password" class="form-control" name="password" required>
            </div>

            <div class="form-group m-0">
                <button type="submit" class="btn btn-primary btn-block">
                    Se connecter
                </button>
            </div>
            <div class="mt-4 text-center">
                Vous n'avez pas de compte? <a href="<?= $router->pathFor('showRegister') ?>">Inscrivez-vous!</a>
            </div>
        </form>
    </div>
</div>