<div class="card">
    <div class="card-body">
        <h4 class="card-title">Inscription</h4>
        <form method="POST" action="<?= $router->pathFor('showRegister') ?>">
            <div class="form-group">
                <label for="pseudo">Pseudonyme</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">@</div>
                    </div>
                    <input id="pseudo" type="text" class="form-control" name="pseudo" required>
                </div>
            </div>

            <div class="form-group">
                <label for="email">Adresse e-mail</label>
                <input id="email" type="email" class="form-control" name="email" required>
            </div>

            <div class="form-group form-row">
                <div class="col">
                    <label for="password">Mot de passe</label>
                    <input id="password" type="password" class="form-control" name="password" required>
                </div>
                <div class="col">
                    <label for="password_conf">Confirmation</label>
                    <input id="password_conf" type="password" class="form-control" name="password_conf" required>
                </div>
            </div>

            <div class="form-group">
                <div class="custom-checkbox custom-control">
                    <input type="checkbox" name="agree" id="agree" class="custom-control-input" required=>
                    <label for="agree" class="custom-control-label">J'accepte les <a href="#" data-toggle="tooltip" data-placement="top" title="Cévide">conditions d'utilisation</a></label>
                </div>
            </div>

            <div class="form-group m-0">
                <button type="submit" class="btn btn-primary btn-block">
                    S'inscrire
                </button>
            </div>
            <div class="mt-4 text-center">
                Vous avez déjà un compte? <a href="<?= $router->pathFor('showLogin') ?>">Connectez-vous!</a>
            </div>
        </form>
    </div>
</div>