<div class="card text-center my-2">

<!--<div class="col-md-6 mb-3">
            <label for="firstName">Entrez votre nom</label>
            <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
</div>
<div class="col-md-6 mb-3">
            <label for="firstName">Entrez le numéro d'item</label>
            <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
</div>-->
  <div class="card-body">  
    La réservation s'est bien enregistré.
  </div> 
</div>