<h2 class="text-center my-5">Modification de liste</h2>
<form id="form_message" method="POST" action="<?= $router->pathFor('updateListe') ?>">
    <input type="hidden" value="<?= $liste->token ?>" name="token"/>
    <input type="hidden" value="<?= $liste->creationToken ?>" name="creationToken"/>
    <div class="form-group">
        <label for="inputName">Insérez un titre</label>
        <input type="text" name="newTitle" class="form-control" id="inputTitle" value="<?= $liste->titre ?>">
    </div>
    <div class="form-group">
        <label for="inputName">Indiquez une date d'expiration</label>
        <input type="date" name="newDate" class="form-control" id="inputDateExpi" value="<?= $liste->expiration ?>">
    </div>
    <div class="form-group">
        <label for="textarea">Ajoutez une description</label>
        <textarea class="form-control" id="textarea" rows="3" name="newDescription"><?= $liste->description ?></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>